/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_CIMthetics_jvma_NativeProxies */

#ifndef _Included_com_CIMthetics_jvma_NativeProxies
#define _Included_com_CIMthetics_jvma_NativeProxies
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaAllocateMemoryForBuffer
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkBuffer;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaAllocateMemoryForBuffer
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaAllocateMemoryForImage
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkImage;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaAllocateMemoryForImage
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaAllocateMemory
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/VkMemoryRequirements;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaAllocateMemory
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaAllocateMemoryPages
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/VkMemoryRequirements;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;JLcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaAllocateMemoryPages
  (JNIEnv *, jobject, jobject, jobject, jobject, jlong, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaBindBufferMemory
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkBuffer;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaBindBufferMemory
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaBindImageMemory
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkImage;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaBindImageMemory
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaBuildStatsString
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Structures/StringReturnValue;Z)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaBuildStatsString
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCheckCorruption
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;I)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCheckCorruption
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCheckPoolCorruption
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaPool;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCheckPoolCorruption
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCreateAllocator
 * Signature: (Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocatorCreateInfo;Lcom/CIMthetics/jvma/Handles/VmaAllocator;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCreateAllocator
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCreateBuffer
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/CreateInfos/VkBufferCreateInfo;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkBuffer;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCreateBuffer
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCreateImage
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/CreateInfos/VkImageCreateInfo;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkImage;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCreateImage
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCreateLostAllocation
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCreateLostAllocation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCreatePool
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaPoolCreateInfo;Lcom/CIMthetics/jvma/Handles/VmaPool;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCreatePool
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaCalculateStats
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Structures/VmaStats;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaCalculateStats
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDefragment
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;[Lcom/CIMthetics/jvma/Handles/VmaAllocation;J[ZLcom/CIMthetics/jvma/Structures/VmaDefragmentationInfo;Lcom/CIMthetics/jvma/Structures/VmaDefragmentationStats;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDefragment
  (JNIEnv *, jobject, jobject, jobjectArray, jlong, jbooleanArray, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDefragmentationBegin
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Structures/VmaDefragmentationInfo2;Lcom/CIMthetics/jvma/Structures/VmaDefragmentationStats;Lcom/CIMthetics/jvma/Handles/VmaDefragmentationContext;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDefragmentationBegin
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDefragmentationEnd
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaDefragmentationContext;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDefragmentationEnd
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDestroyAllocator
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDestroyAllocator
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDestroyBuffer
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkBuffer;Lcom/CIMthetics/jvma/Handles/VmaAllocation;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDestroyBuffer
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDestroyImage
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Handles/VkImage;Lcom/CIMthetics/jvma/Handles/VmaAllocation;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDestroyImage
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaDestroyPool
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaPool;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaDestroyPool
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaFindMemoryTypeIndex
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Ljava/util/EnumSet;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/IntReturnValue;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaFindMemoryTypeIndex
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaFindMemoryTypeIndexForBufferInfo
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/CreateInfos/VkBufferCreateInfo;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Ljava/lang/Integer;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaFindMemoryTypeIndexForBufferInfo
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaFindMemoryTypeIndexForImageInfo
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/CreateInfos/VkImageCreateInfo;Lcom/CIMthetics/jvma/Structures/CreateInfos/VmaAllocationCreateInfo;Ljava/lang/Integer;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaFindMemoryTypeIndexForImageInfo
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaFlushAllocation
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;JJ)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaFlushAllocation
  (JNIEnv *, jobject, jobject, jobject, jlong, jlong);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaFreeMemory
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaFreeMemory
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaFreeMemoryPages
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;JLcom/CIMthetics/jvma/Handles/VmaAllocation;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaFreeMemoryPages
  (JNIEnv *, jobject, jobject, jlong, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaGetAllocationInfo
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Structures/VmaAllocationInfo;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaGetAllocationInfo
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaGetMemoryProperties
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/VkPhysicalDeviceMemoryProperties;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaGetMemoryProperties
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaGetMemoryTypeProperties
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;ILjava/util/EnumSet;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaGetMemoryTypeProperties
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaGetPhysicalDeviceProperties
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Structures/VkPhysicalDeviceProperties;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaGetPhysicalDeviceProperties
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaGetPoolStats
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaPool;Lcom/CIMthetics/jvma/Structures/VmaPoolStats;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaGetPoolStats
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaInvalidateAllocation
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;JJ)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaInvalidateAllocation
  (JNIEnv *, jobject, jobject, jobject, jlong, jlong);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaMakePoolAllocationsLost
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaPool;Ljava/lang/Long;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaMakePoolAllocationsLost
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaMapMemory
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Lcom/CIMthetics/jvma/Handles/MappedData;)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaMapMemory
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaResizeAllocation
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;J)Lcom/CIMthetics/jvulkan/VulkanCore/VK11/Enums/VkResult;
 */
JNIEXPORT jobject JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaResizeAllocation
  (JNIEnv *, jobject, jobject, jobject, jlong);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaSetAllocationUserData
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaSetAllocationUserData
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaSetCurrentFrameIndex
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;I)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaSetCurrentFrameIndex
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaTouchAllocation
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaTouchAllocation
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_CIMthetics_jvma_NativeProxies
 * Method:    vmaUnmapMemory
 * Signature: (Lcom/CIMthetics/jvma/Handles/VmaAllocator;Lcom/CIMthetics/jvma/Handles/VmaAllocation;)V
 */
JNIEXPORT void JNICALL Java_com_CIMthetics_jvma_NativeProxies_vmaUnmapMemory
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
